The following notebook example will allow you to test DPK, without cloning the repo. You can run it either on Google Colab or you can use your local environment (by downloading just the notebook). We use a temporary folder for input and output, but users are encouraged to use their own input folder.

In [1]:
%%capture
!pip install 'data-prep-toolkit-transforms[docling2parquet]==1.1.1.dev0'
!pip install pandas
import urllib.request
import shutil

In [2]:
shutil.os.makedirs("tmp/input", exist_ok=True)
urllib.request.urlretrieve("https://raw.githubusercontent.com/data-prep-kit/data-prep-kit/dev/transforms/language/docling2parquet/test-data/input/archive1.zip", "tmp/input/archive1.zip")
urllib.request.urlretrieve("https://raw.githubusercontent.com/data-prep-kit/data-prep-kit/dev/transforms/language/docling2parquet/test-data/input/redp5110-ch1.pdf", "tmp/input/redp5110-ch1.pdf")

('tmp/input/redp5110-ch1.pdf', <http.client.HTTPMessage at 0x106fd5220>)

In [3]:
from dpk_docling2parquet.transform_python import Docling2Parquet
from dpk_docling2parquet.transform import docling2parquet_contents_types

In [4]:
Docling2Parquet(input_folder= "tmp/input", 
               output_folder= "tmp/output", 
               data_files_to_use=['.pdf', '.zip'],
               docling2parquet_contents_type=docling2parquet_contents_types.JSON).transform()

15:55:44 INFO - docling2parquet parameters are : {'batch_size': -1, 'artifacts_path': None, 'contents_type': <docling2parquet_contents_types.JSON: 'application/json'>, 'do_table_structure': True, 'do_ocr': True, 'ocr_engine': <docling2parquet_ocr_engine.EASYOCR: 'easyocr'>, 'bitmap_area_threshold': 0.05, 'pdf_backend': <docling2parquet_pdf_backend.DLPARSE_V2: 'dlparse_v2'>, 'double_precision': 8}
15:55:44 INFO - pipeline id pipeline_id
15:55:44 INFO - code location None
15:55:44 INFO - data factory data_ is using local data access: input_folder - tmp/input output_folder - tmp/output
15:55:44 INFO - data factory data_ max_files -1, n_sample -1
15:55:44 INFO - data factory data_ Not using data sets, checkpointing False, max files -1, random samples -1, files to use ['.pdf', '.zip'], files to checkpoint ['.parquet']
15:55:44 INFO - orchestrator docling2parquet started at 2025-04-30 15:55:44
15:55:44 INFO - Number of files is 2, source profile {'max_file_size': 0.3013172149658203, 'min_file_size': 0.2757863998413086, 'total_file_size': 0.5771036148071289}
15:55:44 INFO - Initializing models
15:55:48 INFO - Processing archive_doc_filename='2305.03393v1-pg9.pdf'
15:55:49 INFO - Processing archive_doc_filename='2408.09869v1-pg1.pdf'
15:55:50 INFO - Completed 1 files (50.0%) in 0.029 min
15:55:52 INFO - Completed 2 files (100.0%) in 0.068 min
15:55:52 INFO - Done processing 2 files, waiting for flush() completion.
15:55:52 INFO - done flushing in 0.0 sec
15:55:52 INFO - Completed execution in 0.134 min, execution result 0

0

In [5]:
import pyarrow.parquet as pq
import pandas as pd
table = pq.read_table('tmp/output/archive1.parquet')
table.to_pandas()

,filename,contents,num_pages,num_tables,num_doc_elements,document_id,document_hash,ext,hash,size,date_acquired,document_convert_time,source_filename
0,2305.03393v1-pg9.pdf,"{""schema_name"":""DoclingDocument"",""version"":""1....",1,1,9,344e70e5-e76c-4c71-9f75-bba07097d52c,3463920545297462180,pdf,cbea5dc60332b6c118b6f84dd408d07733d60de0a5833f...,37501,2025-04-30T15:55:49.769213,1.408990,archive1.zip
1,2408.09869v1-pg1.pdf,"{""schema_name"":""DoclingDocument"",""version"":""1....",1,0,12,f292bc1b-a3ee-4d42-9046-9aef1233a78a,582377908831471240,pdf,d60e83391f22ce095ba6d8be5147aac1b666a97fed1edd...,8854,2025-04-30T15:55:50.085104,0.314534,archive1.zip

In [6]:
table = pq.read_table('tmp/output/redp5110-ch1.parquet')
table.to_pandas()

,filename,contents,num_pages,num_tables,num_doc_elements,document_id,document_hash,ext,hash,size,date_acquired,document_convert_time,source_filename
0,redp5110-ch1.pdf,"{""schema_name"":""DoclingDocument"",""version"":""1....",5,0,57,799d8c8f-6d1b-444e-a2e2-20d9c460b7f5,74198560999363607,pdf,609845b7d3d8fa99a9dbf8f2dffbe1d83475466f6bf3b1...,38346,2025-04-30T15:55:52.435775,2.34537,redp5110-ch1.pdf