##### **** These pip installs need to be adapted to use the appropriate release level. Alternatively, The venv running the jupyter lab could be pre-configured with a requirement file that includes the right release. Example for transform developers working from git clone:
```
make venv 
source venv/bin/activate 
pip install jupyterlab
```

In [47]:
%%capture
!pip install pandas

In [8]:
import os
os.environ['S3_ACCESS_KEY']=os.environ['COS_DPK_ACCESS_KEY']
os.environ['S3_SECRET_KEY']=os.environ['COS_DPK_SECRET_KEY']
os.environ['S3_ENDPOINT']= "https://s3.us-south.cloud-object-storage.appdomain.cloud"
input_folder="S3://bucket-wikimedia-1/take6_md"
output_folder="S3://bucket-wikimedia-1/test-MT"

##### ***** Import required classes and modules

In [9]:
from data_processing.data_access import DataAccessS3

In [89]:
da=DataAccessS3(config={'input_folder': input_folder,'output_folder': output_folder})

In [90]:
l, _, _=da.get_files_to_process()

In [104]:
import pyarrow.parquet as pq
import pyarrow as pa
import pandas as pd

dataset=None
ndx = 0
for _filename in l:
    byte_array,_=da.get_file(_filename)
    ndx = ndx + 1
    print (f"{ndx}- Processing {_filename}: file size: {len(byte_array)}")
    pqfile=pq.ParquetFile(pa.BufferReader(byte_array))
    patable=pqfile.read().select(['filename', 'document_hash'])
    if dataset is None:
        dataset=patable.to_pandas()
    else:
        dataset=pd.concat([dataset, patable.to_pandas()], ignore_index=True)

1- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_0.ndjson.parquet: file size: 35053613
2- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_1.ndjson.parquet: file size: 35506589
3- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_10.ndjson.parquet: file size: 34491630
4- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_100.ndjson.parquet: file size: 50950761
5- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_101.ndjson.parquet: file size: 52202646
6- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_102.ndjson.parquet: file size: 52989262
7- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_103.ndjson.parquet: file size: 53085169
8- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_104.ndjson.parquet: file size: 53694756
9- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_105.ndjson.parquet: file size: 53821285
10- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_106.ndjson.parquet: file size: 53146835
11- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_107.ndjson.parquet: file size: 52336178
12- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_108.ndjson.parquet: file size: 53465582
13- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_109.ndjson.parquet: file size: 53389607
14- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_11.ndjson.parquet: file size: 32300861
15- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_110.ndjson.parquet: file size: 52801123
16- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_111.ndjson.parquet: file size: 53666576
17- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_112.ndjson.parquet: file size: 52129234
18- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_113.ndjson.parquet: file size: 52113503
19- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_114.ndjson.parquet: file size: 50470716
20- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_115.ndjson.parquet: file size: 50420361
21- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_116.ndjson.parquet: file size: 51995486
22- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_117.ndjson.parquet: file size: 51654327
23- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_118.ndjson.parquet: file size: 52849524
24- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_119.ndjson.parquet: file size: 52977955
25- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_12.ndjson.parquet: file size: 33164891
26- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_120.ndjson.parquet: file size: 52333201
27- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_121.ndjson.parquet: file size: 50803402
28- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_122.ndjson.parquet: file size: 51451827
29- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_123.ndjson.parquet: file size: 50558701
30- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_124.ndjson.parquet: file size: 52954500
31- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_125.ndjson.parquet: file size: 53993895
32- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_126.ndjson.parquet: file size: 53542265
33- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_127.ndjson.parquet: file size: 53347954
34- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_128.ndjson.parquet: file size: 53984834
35- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_129.ndjson.parquet: file size: 52395407
36- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_13.ndjson.parquet: file size: 32775564
37- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_130.ndjson.parquet: file size: 51025806
38- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_131.ndjson.parquet: file size: 50934964
39- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_132.ndjson.parquet: file size: 51847328
40- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_133.ndjson.parquet: file size: 52572095
41- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_134.ndjson.parquet: file size: 52016169
42- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_135.ndjson.parquet: file size: 52479614
43- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_136.ndjson.parquet: file size: 52656567
44- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_137.ndjson.parquet: file size: 53104020
45- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_138.ndjson.parquet: file size: 52956070
46- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_139.ndjson.parquet: file size: 51120054
47- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_14.ndjson.parquet: file size: 31397742
48- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_140.ndjson.parquet: file size: 50866075
49- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_141.ndjson.parquet: file size: 50939929
50- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_142.ndjson.parquet: file size: 53038450
51- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_143.ndjson.parquet: file size: 53518343
52- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_144.ndjson.parquet: file size: 54128855
53- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_145.ndjson.parquet: file size: 53409236
54- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_146.ndjson.parquet: file size: 53740763
55- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_147.ndjson.parquet: file size: 54185032
56- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_148.ndjson.parquet: file size: 53474298
57- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_149.ndjson.parquet: file size: 52914316
58- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_15.ndjson.parquet: file size: 31145378
59- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_150.ndjson.parquet: file size: 53251448
60- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_151.ndjson.parquet: file size: 53135923
61- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_152.ndjson.parquet: file size: 53581233
62- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_153.ndjson.parquet: file size: 52744565
63- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_154.ndjson.parquet: file size: 53116707
64- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_155.ndjson.parquet: file size: 53530604
65- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_156.ndjson.parquet: file size: 53645998
66- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_157.ndjson.parquet: file size: 53035546
67- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_158.ndjson.parquet: file size: 52541772
68- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_159.ndjson.parquet: file size: 52265446
69- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_16.ndjson.parquet: file size: 34064779
70- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_160.ndjson.parquet: file size: 52539290
71- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_161.ndjson.parquet: file size: 54123730
72- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_162.ndjson.parquet: file size: 54268681
73- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_163.ndjson.parquet: file size: 54285617
74- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_164.ndjson.parquet: file size: 53170057
75- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_165.ndjson.parquet: file size: 53706014
76- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_166.ndjson.parquet: file size: 52629327
77- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_167.ndjson.parquet: file size: 53126732
78- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_168.ndjson.parquet: file size: 53722500
79- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_169.ndjson.parquet: file size: 53266690
80- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_17.ndjson.parquet: file size: 34974260
81- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_170.ndjson.parquet: file size: 53475232
82- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_171.ndjson.parquet: file size: 52918853
83- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_172.ndjson.parquet: file size: 51778513
84- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_173.ndjson.parquet: file size: 52158666
85- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_174.ndjson.parquet: file size: 52260864
86- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_175.ndjson.parquet: file size: 52011476
87- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_176.ndjson.parquet: file size: 53206662
88- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_177.ndjson.parquet: file size: 54471882
89- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_178.ndjson.parquet: file size: 53670535
90- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_179.ndjson.parquet: file size: 53326714
91- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_18.ndjson.parquet: file size: 31700795
92- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_180.ndjson.parquet: file size: 52820309
93- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_181.ndjson.parquet: file size: 52951620
94- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_182.ndjson.parquet: file size: 53358177
95- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_183.ndjson.parquet: file size: 54249557
96- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_184.ndjson.parquet: file size: 53512031
97- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_185.ndjson.parquet: file size: 52780228
98- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_186.ndjson.parquet: file size: 53332014
99- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_187.ndjson.parquet: file size: 53214395
100- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_188.ndjson.parquet: file size: 53658573
101- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_189.ndjson.parquet: file size: 54303826
102- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_19.ndjson.parquet: file size: 32160423
103- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_190.ndjson.parquet: file size: 54576969
104- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_191.ndjson.parquet: file size: 55118038
105- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_192.ndjson.parquet: file size: 54180517
106- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_193.ndjson.parquet: file size: 54973006
107- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_194.ndjson.parquet: file size: 54839335
108- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_195.ndjson.parquet: file size: 53735561
109- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_196.ndjson.parquet: file size: 54862135
110- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_197.ndjson.parquet: file size: 54248740
111- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_198.ndjson.parquet: file size: 53676902
112- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_199.ndjson.parquet: file size: 53432339
113- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_2.ndjson.parquet: file size: 35194556
114- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_20.ndjson.parquet: file size: 34641954
115- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_200.ndjson.parquet: file size: 55064611
116- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_201.ndjson.parquet: file size: 55774613
117- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_202.ndjson.parquet: file size: 54790194
118- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_203.ndjson.parquet: file size: 55804634
119- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_204.ndjson.parquet: file size: 56454005
120- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_205.ndjson.parquet: file size: 55453006
121- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_206.ndjson.parquet: file size: 54604548
122- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_207.ndjson.parquet: file size: 53156216
123- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_208.ndjson.parquet: file size: 52492273
124- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_209.ndjson.parquet: file size: 53428570
125- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_21.ndjson.parquet: file size: 38187021
126- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_210.ndjson.parquet: file size: 53041816
127- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_211.ndjson.parquet: file size: 55019679
128- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_212.ndjson.parquet: file size: 53574585
129- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_213.ndjson.parquet: file size: 54276559
130- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_214.ndjson.parquet: file size: 54875017
131- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_215.ndjson.parquet: file size: 54338316
132- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_216.ndjson.parquet: file size: 54390121
133- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_217.ndjson.parquet: file size: 54737684
134- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_218.ndjson.parquet: file size: 55362109
135- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_219.ndjson.parquet: file size: 55728916
136- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_22.ndjson.parquet: file size: 43509414
137- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_220.ndjson.parquet: file size: 53696793
138- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_221.ndjson.parquet: file size: 54508112
139- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_222.ndjson.parquet: file size: 53856247
140- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_223.ndjson.parquet: file size: 52227861
141- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_224.ndjson.parquet: file size: 52541627
142- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_225.ndjson.parquet: file size: 54017532
143- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_226.ndjson.parquet: file size: 52820684
144- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_227.ndjson.parquet: file size: 55163102
145- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_228.ndjson.parquet: file size: 54991907
146- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_229.ndjson.parquet: file size: 55498278
147- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_23.ndjson.parquet: file size: 40335174
148- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_230.ndjson.parquet: file size: 56340531
149- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_231.ndjson.parquet: file size: 55953400
150- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_232.ndjson.parquet: file size: 57356496
151- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_233.ndjson.parquet: file size: 56336364
152- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_234.ndjson.parquet: file size: 56971196
153- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_235.ndjson.parquet: file size: 56608054
154- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_236.ndjson.parquet: file size: 55927402
155- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_237.ndjson.parquet: file size: 56236742
156- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_238.ndjson.parquet: file size: 56728735
157- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_239.ndjson.parquet: file size: 55851646
158- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_24.ndjson.parquet: file size: 33378405
159- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_240.ndjson.parquet: file size: 55489866
160- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_241.ndjson.parquet: file size: 56311509
161- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_242.ndjson.parquet: file size: 56064901
162- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_243.ndjson.parquet: file size: 55886783
163- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_244.ndjson.parquet: file size: 56603977
164- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_245.ndjson.parquet: file size: 55835704
165- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_246.ndjson.parquet: file size: 57302707
166- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_247.ndjson.parquet: file size: 56839648
167- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_248.ndjson.parquet: file size: 56186477
168- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_249.ndjson.parquet: file size: 57343448
169- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_25.ndjson.parquet: file size: 32325183
170- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_250.ndjson.parquet: file size: 56079841
171- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_251.ndjson.parquet: file size: 57145242
172- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_252.ndjson.parquet: file size: 56064613
173- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_253.ndjson.parquet: file size: 56263556
174- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_254.ndjson.parquet: file size: 56646220
175- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_255.ndjson.parquet: file size: 56395033
176- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_256.ndjson.parquet: file size: 55510669
177- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_257.ndjson.parquet: file size: 56283645
178- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_258.ndjson.parquet: file size: 55471394
179- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_259.ndjson.parquet: file size: 54956217
180- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_26.ndjson.parquet: file size: 32553540
181- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_260.ndjson.parquet: file size: 55775797
182- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_261.ndjson.parquet: file size: 56505990
183- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_262.ndjson.parquet: file size: 55860026
184- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_263.ndjson.parquet: file size: 55813636
185- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_264.ndjson.parquet: file size: 56857505
186- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_265.ndjson.parquet: file size: 56974073
187- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_266.ndjson.parquet: file size: 58449696
188- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_267.ndjson.parquet: file size: 60028519
189- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_268.ndjson.parquet: file size: 59521615
190- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_269.ndjson.parquet: file size: 59854046
191- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_27.ndjson.parquet: file size: 33784649
192- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_270.ndjson.parquet: file size: 61310563
193- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_271.ndjson.parquet: file size: 62116397
194- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_272.ndjson.parquet: file size: 62780466
195- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_273.ndjson.parquet: file size: 62913390

In [105]:
len(dataset)

7128273

In [120]:
hash_counts=dataset['document_hash'].value_counts()
dataset['hash_count']=dataset['document_hash'].map(hash_counts)
dataset.sort_values(by='hash_count', ascending=False)

                                 filename         document_hash  hash_count
5391239  enwiki_namespace_0_396_1494.html   4645722594882866820           3
5391245  enwiki_namespace_0_396_1500.html   4645722594882866820           3
5391234  enwiki_namespace_0_396_1489.html   4645722594882866820           3
5391425  enwiki_namespace_0_396_1680.html  12771608352772316580           2
5383791   enwiki_namespace_0_395_909.html  10600707456625690885           2
...                                   ...                   ...         ...
2376087  enwiki_namespace_0_185_7325.html   3907772245686668795           1
2376086  enwiki_namespace_0_185_7324.html  12870594153745355973           1
2376085  enwiki_namespace_0_185_7323.html   2111910482168064541           1
2376084  enwiki_namespace_0_185_7322.html  13341779551056146637           1
7128272  enwiki_namespace_0_99_24190.html  18284615490288699418           1

[7128273 rows x 3 columns]

In [114]:
duplicates=dataset[dataset['hash_count'] == 3]
duplicates.sort_values(by='document_hash', ascending=False)

                                 filename        document_hash  hash_count
5391234  enwiki_namespace_0_396_1489.html  4645722594882866820           3
5391239  enwiki_namespace_0_396_1494.html  4645722594882866820           3
5391245  enwiki_namespace_0_396_1500.html  4645722594882866820           3

In [119]:
duplicates=dataset[dataset['hash_count'] == 2]
pd.set_option('display.max_rows', len(duplicates))
duplicates.sort_values(by='document_hash', ascending=False)

                                 filename         document_hash  hash_count
5376197   enwiki_namespace_0_394_247.html   9944271733273349128           2
5376196   enwiki_namespace_0_394_246.html   9944271733273349128           2
5310127  enwiki_namespace_0_387_4763.html   9669684869341135938           2
5310134  enwiki_namespace_0_387_4770.html   9669684869341135938           2
5280400  enwiki_namespace_0_383_1597.html   9656007629735751019           2
5280401  enwiki_namespace_0_383_1598.html   9656007629735751019           2
5468474  enwiki_namespace_0_402_5906.html   9617237508520696951           2
5468475  enwiki_namespace_0_402_5907.html   9617237508520696951           2
5381572  enwiki_namespace_0_394_5624.html   9609734338291521026           2
5381577  enwiki_namespace_0_394_5629.html   9609734338291521026           2
5369082  enwiki_namespace_0_392_6426.html   9595184341439678156           2
5369005  enwiki_namespace_0_392_6349.html   9595184341439678156           2
5370435  enwiki_namespace_0_393_1329.html   9557815879112965264           2
5370441  enwiki_namespace_0_393_1335.html   9557815879112965264           2
5472925  enwiki_namespace_0_403_3428.html   9490292931208588191           2
5472926  enwiki_namespace_0_403_3429.html   9490292931208588191           2
5316316  enwiki_namespace_0_388_4828.html   9434436591373538333           2
5316308  enwiki_namespace_0_388_4820.html   9434436591373538333           2
5384686  enwiki_namespace_0_395_1805.html   9405495562007325535           2
5384685  enwiki_namespace_0_395_1804.html   9405495562007325535           2
5322851  enwiki_namespace_0_389_5211.html   9404099158807882830           2
5322844  enwiki_namespace_0_389_5204.html   9404099158807882830           2
5306299   enwiki_namespace_0_387_935.html   9373535196752735516           2
5306293   enwiki_namespace_0_387_929.html   9373535196752735516           2
5387857  enwiki_namespace_0_395_4977.html   9348405143222157279           2
5387863  enwiki_namespace_0_395_4983.html   9348405143222157279           2
5467453  enwiki_namespace_0_402_4885.html   9264736759913539286           2
5467456  enwiki_namespace_0_402_4888.html   9264736759913539286           2
5384212  enwiki_namespace_0_395_1331.html   9234952305844748322           2
5384198  enwiki_namespace_0_395_1317.html   9234952305844748322           2
5319514  enwiki_namespace_0_389_1873.html   9215180897101052883           2
5319505  enwiki_namespace_0_389_1864.html   9215180897101052883           2
5468231  enwiki_namespace_0_402_5663.html   9191273709383459432           2
5468258  enwiki_namespace_0_402_5690.html   9191273709383459432           2
5468860  enwiki_namespace_0_402_6292.html    912863943903044100           2
5468831  enwiki_namespace_0_402_6263.html    912863943903044100           2
5385161  enwiki_namespace_0_395_2281.html   9110219388891614171           2
5385167  enwiki_namespace_0_395_2287.html   9110219388891614171           2
5470276   enwiki_namespace_0_403_779.html   9098970719214817319           2
5470274   enwiki_namespace_0_403_777.html   9098970719214817319           2
5290998  enwiki_namespace_0_384_5406.html   9003340247615679116           2
5290986  enwiki_namespace_0_384_5394.html   9003340247615679116           2
5350103   enwiki_namespace_0_390_448.html   8959881682294715412           2
5350088   enwiki_namespace_0_390_433.html   8959881682294715412           2
5451311  enwiki_namespace_0_400_1842.html   8863207170083269163           2
5451323  enwiki_namespace_0_400_1854.html   8863207170083269163           2
5371319  enwiki_namespace_0_393_2217.html   8797321745651690345           2
5371054  enwiki_namespace_0_393_1951.html   8797321745651690345           2
5392718  enwiki_namespace_0_396_2973.html   8757066871183112292           2
5392723  enwiki_namespace_0_396_2978.html   8757066871183112292           2
5402708  enwiki_namespace_0_398_1238.html   8718106036275695980           2
5402747  enwiki_namespace_0_398_1277.html   8718106036275695980           2
5383345   enwiki_namespace_0_395_463.html   8674724011277272619           2
5383362   enwiki_namespace_0_395_480.html   8674724011277272619           2
5409289  enwiki_namespace_0_399_2100.html   8663376523426599433           2
5409290  enwiki_namespace_0_399_2101.html   8663376523426599433           2
5365749  enwiki_namespace_0_392_3093.html   8633959574914070754           2
5365755  enwiki_namespace_0_392_3099.html   8633959574914070754           2
5454861  enwiki_namespace_0_400_5396.html   8612980733759921938           2
5454857  enwiki_namespace_0_400_5392.html   8612980733759921938           2
5308238  enwiki_namespace_0_387_2874.html   8560388654756107625           2
5308248  enwiki_namespace_0_387_2884.html   8560388654756107625           2
5393580  enwiki_namespace_0_396_3836.html   8554975980777643784           2
5393586  enwiki_namespace_0_396_3842.html   8554975980777643784           2
5407636   enwiki_namespace_0_399_447.html   8554765188461244979           2
5407646   enwiki_namespace_0_399_457.html   8554765188461244979           2
5391750  enwiki_namespace_0_396_2005.html   8520643981318614767           2
5391756  enwiki_namespace_0_396_2011.html   8520643981318614767           2
5412012  enwiki_namespace_0_399_4823.html   8364319236979399225           2
5412020  enwiki_namespace_0_399_4831.html   8364319236979399225           2
5461618  enwiki_namespace_0_401_5608.html   8333097822687305913           2
5461596  enwiki_namespace_0_401_5586.html   8333097822687305913           2
5308105  enwiki_namespace_0_387_2741.html    830816906617279065           2
5308095  enwiki_namespace_0_387_2731.html    830816906617279065           2
5407459   enwiki_namespace_0_399_270.html   8143912239678326938           2
5407473   enwiki_namespace_0_399_284.html   8143912239678326938           2
5391115  enwiki_namespace_0_396_1370.html   8017581090375920578           2
5391114  enwiki_namespace_0_396_1369.html   8017581090375920578           2
5465094  enwiki_namespace_0_402_2525.html   7956614855267122406           2
5465093  enwiki_namespace_0_402_2524.html   7956614855267122406           2
5400268  enwiki_namespace_0_397_4866.html   7954599203219572631           2
5400274  enwiki_namespace_0_397_4872.html   7954599203219572631           2
5301165  enwiki_namespace_0_386_2400.html   7938481987446288565           2
5301156  enwiki_namespace_0_386_2391.html   7938481987446288565           2
5352115  enwiki_namespace_0_390_2460.html   7908669912708261037           2
5352097  enwiki_namespace_0_390_2442.html   7908669912708261037           2
5377204  enwiki_namespace_0_394_1254.html   7867144027843526440           2
5377189  enwiki_namespace_0_394_1239.html   7867144027843526440           2
5370659  enwiki_namespace_0_393_1556.html   7834032433145961738           2
5370665  enwiki_namespace_0_393_1562.html   7834032433145961738           2
5363774  enwiki_namespace_0_392_1118.html   7803897011766951954           2
5363780  enwiki_namespace_0_392_1124.html   7803897011766951954           2
5465889  enwiki_namespace_0_402_3321.html   7646841043118007433           2
5465888  enwiki_namespace_0_402_3320.html   7646841043118007433           2
5362413  enwiki_namespace_0_391_6604.html    763901526999677763           2
5362420  enwiki_namespace_0_391_6611.html    763901526999677763           2
5371634  enwiki_namespace_0_393_2532.html   7617205244129017898           2
5371641  enwiki_namespace_0_393_2539.html   7617205244129017898           2
5364848  enwiki_namespace_0_392_2192.html    746779519622633507           2
5364869  enwiki_namespace_0_392_2213.html    746779519622633507           2
5406362  enwiki_namespace_0_398_4899.html   7352378569814693483           2
5406366  enwiki_namespace_0_398_4903.html   7352378569814693483           2
5314916  enwiki_namespace_0_388_3428.html   7337665664825689016           2
5314924  enwiki_namespace_0_388_3436.html   7337665664825689016           2
5472624  enwiki_namespace_0_403_3127.html   7335776242723445087           2
5472625  enwiki_namespace_0_403_3128.html   7335776242723445087           2
5310721  enwiki_namespace_0_387_5357.html   7253110089434811052           2
5310728  enwiki_namespace_0_387_5364.html   7253110089434811052           2
5399381  enwiki_namespace_0_397_3979.html   7251463420424023140           2
5399376  enwiki_namespace_0_397_3974.html   7251463420424023140           2
5464754  enwiki_namespace_0_402_2185.html   7245706162888619309           2
5464755  enwiki_namespace_0_402_2186.html   7245706162888619309           2
5404438  enwiki_namespace_0_398_2971.html   7177293790706723434           2
5404444  enwiki_namespace_0_398_2977.html   7177293790706723434           2
5399897  enwiki_namespace_0_397_4495.html   6955884471565272214           2
5399915  enwiki_namespace_0_397_4513.html   6955884471565272214           2
5405930  enwiki_namespace_0_398_4465.html   6892487103105053956           2
5405920  enwiki_namespace_0_398_4455.html   6892487103105053956           2
5281946  enwiki_namespace_0_383_3146.html    685817613862609092           2
5281955  enwiki_namespace_0_383_3155.html    685817613862609092           2
5375735  enwiki_namespace_0_393_6634.html   6802854000540240607           2
5375742  enwiki_namespace_0_393_6641.html   6802854000540240607           2
5296935  enwiki_namespace_0_385_4805.html   6789664917598532175           2
5296943  enwiki_namespace_0_385_4813.html   6789664917598532175           2
5452028  enwiki_namespace_0_400_2559.html   6710249116559544954           2
5452030  enwiki_namespace_0_400_2561.html   6710249116559544954           2
5360875  enwiki_namespace_0_391_5066.html   6687225426085011722           2
5360861  enwiki_namespace_0_391_5052.html   6687225426085011722           2
5303742  enwiki_namespace_0_386_4980.html   6670515816163874596           2
5303696  enwiki_namespace_0_386_4934.html   6670515816163874596           2
5292226    enwiki_namespace_0_385_95.html   6606486667529397455           2
5292236   enwiki_namespace_0_385_105.html   6606486667529397455           2
5364501  enwiki_namespace_0_392_1845.html   6543652901814448088           2
5364500  enwiki_namespace_0_392_1844.html   6543652901814448088           2
5402723  enwiki_namespace_0_398_1253.html   6502298214017776897           2
5402733  enwiki_namespace_0_398_1263.html   6502298214017776897           2
5470524  enwiki_namespace_0_403_1027.html    644212781699710130           2
5470526  enwiki_namespace_0_403_1029.html    644212781699710130           2
5350022   enwiki_namespace_0_390_367.html   6428483812082344054           2
5350014   enwiki_namespace_0_390_359.html   6428483812082344054           2
5392919  enwiki_namespace_0_396_3174.html    630899211659142306           2
5392925  enwiki_namespace_0_396_3180.html    630899211659142306           2
5294956  enwiki_namespace_0_385_2826.html   6248473702566375262           2
5294995  enwiki_namespace_0_385_2865.html   6248473702566375262           2
5371097  enwiki_namespace_0_393_1994.html   6208395352207930043           2
5371104  enwiki_namespace_0_393_2001.html   6208395352207930043           2
5386501  enwiki_namespace_0_395_3621.html   6101277410990415427           2
5386524  enwiki_namespace_0_395_3644.html   6101277410990415427           2
5357219  enwiki_namespace_0_391_1407.html   6007409541774342004           2
5357224  enwiki_namespace_0_391_1412.html   6007409541774342004           2
5295006  enwiki_namespace_0_385_2876.html   5972925998166963256           2
5294961  enwiki_namespace_0_385_2831.html   5972925998166963256           2
5308798  enwiki_namespace_0_387_3434.html   5848815406387934002           2
5308778  enwiki_namespace_0_387_3414.html   5848815406387934002           2
5317933   enwiki_namespace_0_389_289.html   5830095960795955859           2
5317989   enwiki_namespace_0_389_345.html   5830095960795955859           2
5293231  enwiki_namespace_0_385_1101.html   5819399018467767764           2
5293252  enwiki_namespace_0_385_1122.html   5819399018467767764           2
5375016  enwiki_namespace_0_393_5915.html   5673110497069755345           2
5375039  enwiki_namespace_0_393_5938.html   5673110497069755345           2
5377721  enwiki_namespace_0_394_1771.html   5638488622346968492           2
5377714  enwiki_namespace_0_394_1764.html   5638488622346968492           2
5375795  enwiki_namespace_0_393_6694.html   5596079545374170467           2
5375803  enwiki_namespace_0_393_6702.html   5596079545374170467           2
5356610   enwiki_namespace_0_391_793.html     55134565816007861           2
5356611   enwiki_namespace_0_391_794.html     55134565816007861           2
5304937  enwiki_namespace_0_386_6175.html   5469353133296258233           2
5304957  enwiki_namespace_0_386_6195.html   5469353133296258233           2
5465460  enwiki_namespace_0_402_2892.html   5452068482363671109           2
5465459  enwiki_namespace_0_402_2891.html   5452068482363671109           2
5157522  enwiki_namespace_0_370_6051.html   5428039888155847131           2
5376441   enwiki_namespace_0_394_491.html   5428039888155847131           2
5402761  enwiki_namespace_0_398_1291.html    536437561269248408           2
5402712  enwiki_namespace_0_398_1242.html    536437561269248408           2
5385891  enwiki_namespace_0_395_3011.html   5341301317811222069           2
5385909  enwiki_namespace_0_395_3029.html   5341301317811222069           2
5396276   enwiki_namespace_0_397_874.html   5334710569923041585           2
5396253   enwiki_namespace_0_397_851.html   5334710569923041585           2
5382704  enwiki_namespace_0_394_6757.html   5301667325899213958           2
5382709  enwiki_namespace_0_394_6762.html   5301667325899213958           2
5390530   enwiki_namespace_0_396_785.html   5271368961130662153           2
5390524   enwiki_namespace_0_396_779.html   5271368961130662153           2
5410924  enwiki_namespace_0_399_3735.html   5266405883607219586           2
5410929  enwiki_namespace_0_399_3740.html   5266405883607219586           2
5403310  enwiki_namespace_0_398_1840.html   5251787599906372439           2
5403308  enwiki_namespace_0_398_1838.html   5251787599906372439           2
5452484  enwiki_namespace_0_400_3017.html   5246187457491690164           2
5452483  enwiki_namespace_0_400_3016.html   5246187457491690164           2
5308742  enwiki_namespace_0_387_3378.html   5135552653419482583           2
5308732  enwiki_namespace_0_387_3368.html   5135552653419482583           2
5379760  enwiki_namespace_0_394_3811.html   5120022860378922045           2
5379753  enwiki_namespace_0_394_3804.html   5120022860378922045           2
5403816  enwiki_namespace_0_398_2348.html   5083480963825936782           2
5403815  enwiki_namespace_0_398_2347.html   5083480963825936782           2
5472611  enwiki_namespace_0_403_3114.html   5020219280205427114           2
5472610  enwiki_namespace_0_403_3113.html   5020219280205427114           2
5354311  enwiki_namespace_0_390_4659.html   5000918262905780851           2
5354340  enwiki_namespace_0_390_4688.html   5000918262905780851           2
5282999  enwiki_namespace_0_383_4200.html   4965315674778236252           2
5282979  enwiki_namespace_0_383_4180.html   4965315674778236252           2
5368002  enwiki_namespace_0_392_5346.html   4951244425059605901           2
5368009  enwiki_namespace_0_392_5353.html   4951244425059605901           2
5393984  enwiki_namespace_0_396_4240.html   4921724894259163079           2
5393989  enwiki_namespace_0_396_4245.html   4921724894259163079           2
5466430  enwiki_namespace_0_402_3862.html   4889819898186254052           2
5466431  enwiki_namespace_0_402_3863.html   4889819898186254052           2
5319154  enwiki_namespace_0_389_1510.html    483746330802714529           2
5319162  enwiki_namespace_0_389_1518.html    483746330802714529           2
5399602  enwiki_namespace_0_397_4200.html   4833307677901509715           2
5399608  enwiki_namespace_0_397_4206.html   4833307677901509715           2
5471433  enwiki_namespace_0_403_1936.html   4827938082292920300           2
5471432  enwiki_namespace_0_403_1935.html   4827938082292920300           2
5358213  enwiki_namespace_0_391_2403.html   4803915837751389801           2
5358226  enwiki_namespace_0_391_2416.html   4803915837751389801           2
5313632  enwiki_namespace_0_388_2144.html   4764988163318459819           2
5313633  enwiki_namespace_0_388_2145.html   4764988163318459819           2
5374725  enwiki_namespace_0_393_5624.html   4710890638718409219           2
5374731  enwiki_namespace_0_393_5630.html   4710890638718409219           2
5452262  enwiki_namespace_0_400_2794.html   4661650344701692820           2
5452260  enwiki_namespace_0_400_2792.html   4661650344701692820           2
5450682  enwiki_namespace_0_400_1213.html   4579238068235607629           2
5450678  enwiki_namespace_0_400_1209.html   4579238068235607629           2
5455889  enwiki_namespace_0_400_6424.html   4572853726042415245           2
5454365  enwiki_namespace_0_400_4899.html   4572853726042415245           2
5396171   enwiki_namespace_0_397_769.html   4527653245451237328           2
5396180   enwiki_namespace_0_397_778.html   4527653245451237328           2
5457669  enwiki_namespace_0_401_1655.html   4478261766050847595           2
5457668  enwiki_namespace_0_401_1654.html   4478261766050847595           2
5393236  enwiki_namespace_0_396_3491.html   4449906997047853883           2
5393223  enwiki_namespace_0_396_3478.html   4449906997047853883           2
5317042  enwiki_namespace_0_388_5554.html   4449373918030238682           2
5317027  enwiki_namespace_0_388_5539.html   4449373918030238682           2
5451235  enwiki_namespace_0_400_1766.html   4370835771370940279           2
5451239  enwiki_namespace_0_400_1770.html   4370835771370940279           2
5465373  enwiki_namespace_0_402_2805.html   4050739630227712905           2
5465374  enwiki_namespace_0_402_2806.html   4050739630227712905           2
5411282  enwiki_namespace_0_399_4093.html   3964599696955654815           2
5411277  enwiki_namespace_0_399_4088.html   3964599696955654815           2
5387583  enwiki_namespace_0_395_4703.html   3938645088672489572           2
5387540  enwiki_namespace_0_395_4660.html   3938645088672489572           2
5361780  enwiki_namespace_0_391_5971.html   3893375556176552847           2
5361773  enwiki_namespace_0_391_5964.html   3893375556176552847           2
5366456  enwiki_namespace_0_392_3800.html   3806290371969542782           2
5366463  enwiki_namespace_0_392_3807.html   3806290371969542782           2
5395073  enwiki_namespace_0_396_5329.html   3730408518615109760           2
5395079  enwiki_namespace_0_396_5335.html   3730408518615109760           2
5369612   enwiki_namespace_0_393_506.html   3728117420205046809           2
5369653   enwiki_namespace_0_393_547.html   3728117420205046809           2
5380475  enwiki_namespace_0_394_4526.html   3708980655745581122           2
5380461  enwiki_namespace_0_394_4512.html   3708980655745581122           2
5408799  enwiki_namespace_0_399_1610.html   3688119269829452247           2
5408803  enwiki_namespace_0_399_1614.html   3688119269829452247           2
5297606  enwiki_namespace_0_385_5477.html    365781489029108955           2
5297646  enwiki_namespace_0_385_5517.html    365781489029108955           2
5358527  enwiki_namespace_0_391_2717.html   3601237148041201227           2
5358522  enwiki_namespace_0_391_2712.html   3601237148041201227           2
5371139  enwiki_namespace_0_393_2036.html    355890139949426179           2
5371125  enwiki_namespace_0_393_2022.html    355890139949426179           2
5411360  enwiki_namespace_0_399_4171.html   3547203814443919823           2
5411365  enwiki_namespace_0_399_4176.html   3547203814443919823           2
5290207  enwiki_namespace_0_384_4614.html   3372441803911332731           2
5290216  enwiki_namespace_0_384_4623.html   3372441803911332731           2

In [121]:
pqfile.read()

pyarrow.Table
filename: string
contents: string
num_pages: int64
num_tables: int64
num_doc_elements: int64
document_id: string
document_hash: string
ext: string
hash: string
size: int64
date_acquired: string
document_convert_time: double
source_filename: string
----
filename: [["enwiki_namespace_0_99_0.html","enwiki_namespace_0_99_1.html","enwiki_namespace_0_99_2.html","enwiki_namespace_0_99_3.html","enwiki_namespace_0_99_4.html",...,"enwiki_namespace_0_99_24186.html","enwiki_namespace_0_99_24187.html","enwiki_namespace_0_99_24188.html","enwiki_namespace_0_99_24189.html","enwiki_namespace_0_99_24190.html"]]
contents: [["# Stenoma gemellata

Species of moth

<!-- image -->

| Stenoma gemellata               | Stenoma gemellata               |
|---------------------------------|---------------------------------|
| Scientific classification       | Scientific classification       |
| Domain:                         | Eukaryota                       |
| Kingdom:                        | Animalia                        |
| Phylum:                         | Arthropoda                      |
| Class:                          | Insecta                         |
| Order:                          | Lepidoptera                     |
| Family:                         | Depressariidae                  |
| Genus:                          | Stenoma                         |
| Species:                        | S. gemellata                    |
| Binomial name                   | Binomial name                   |
| Stenoma gemellata Meyrick, 1916 | Stenoma gemellata Meyrick, 1916 |

Stenoma gemellata is a moth of the family Depressariidae. It is found in French Guiana.[1]

The wingspan is 17-18 mm. The forewings are whitish with the stigmata black, the plical and first discal large and round, the plical very obliquely posterior, the second discal small and transverse. There are some scattered blackish scales above and beyond the cell scarcely indicating a postmedian line and there is a curved line of cloudy dots of blackish irroration from four-fifths of the costa to the dorsum before the tornus, indented above the middle. A marginal series of black dots is found around the apex and termen. The hindwings are whitish.[2]

## References

Wikimedia Commons has media related to Stenoma gemellata.

1. ↑ "Stenoma Zeller, 1839" at Markku Savela's Lepidoptera and Some Other Life Forms
2. ↑ Exotic Microlepidoptera 1 (17): 524 This article incorporates text from this source, which is in the public domain.
Public Domain

<!-- image -->

| Taxon identifiers   | Taxon identifiers                                                                  |
|---------------------|------------------------------------------------------------------------------------|
| Stenoma gemellata   | Wikidata: Q14397249  EoL: 943173  GBIF: 1836441  IRMNG: 10261302  LepIndex: 116447 |

- v
- t
- e","# Tartu Art School

Art school in Tartu, Estonia

<!-- image -->

<!-- image -->

| Tartu Kunstikool   | Tartu Kunstikool                                                                     |
|--------------------|--------------------------------------------------------------------------------------|
|                    |                                                                                      |
| Former names       | Tartu Visual Art School                                                              |
| Type               | Upper secondary vocational school                                                    |
| Established        | 1951; 74 years ago (1951)                                                            |
| Director           | Kadi Kreis                                                                           |
| Students           | 120 (2012)                                                                           |
| Location           | Tartu, Estonia 58°22′52″N 26°43′13″E﻿ / ﻿58.38111°N 26.72028°E﻿ / 58.38111; 26.72028 |
| Affiliations       | ArtECult                                                                             |
| Website            | Official website                                                                     |

Tartu Art School (Estonian: Tartu Kunstikool) is an upper secondary vocational art school in the city of Tartu, Estonia. TAS provides study programs for aspiring decorator-stylists (interior designers), print media designer-desktop publishers, 3D-modellers and illustrators.[1]

## History

The history of Tartu Art School is closely linked to the Tartu National Art Institute and therefore to the influential Pallas art school which was renamed the Konrad Mägi Higher State  School of Art in the early Soviet era. In 1944 the school adopted the name National Art Institute of Tartu.

In the 1940s the institutions that provided higher art education in Estonia were in both Tallinn and Tartu. However, at the end of the decade the Soviet Council of Ministers ruled that the National Art Institute of Tartu be united with the National Art Institute of Tallinn, concentrating all the higher education in art in the capital. The only function that the former National Art Institute of Tartu performed at the time was preparing future students set for the institute in Tallinn and training aspiring art teachers.

Tartu Visual Art School opened its doors on July 1, 1951 which is also considered the official birthday of Tartu Art School (the name was officially changed in 1960). In its first year of existence only courses in art pedagogy were taught with sculpting, decorating and fashion design disciplines being added to the curriculum during the next few years.

The next couple of decades were a time of stable growth for TAS. During the 90's the school moved to its own  building on Tähe street. TAS relocated again in early 2010 and is currently situated on Eha street (Eha 41) in the district of Karlova in Tartu.[2]

## Organization

Students who enroll at Tartu Art School can choose one of four disciplines: interior design (decorator-stylists), print media design-desktop publishing, illustration and 3D-modelling. In addition to basic art studies (drawing, painting, graphics, sculpting, composition, typography, chromatics etc.), TAS study programs include animation and photography. Depending on the field of study, students need to have graduated from a primary school or a secondary school. A youth contest which has been held for nearly 6 years gives a few aspiring TAS students a chance to enroll at the school without having to take the entrance exams. Students graduate after 3.5 years. The academic year begins in September and is divided into two semesters. Additionally, TAS has individual study programs for adults. About 50 teachers work at TAS and the current headmistress is Kadi Kreis (since August 2000).

## Traditions

- A travelling trophy - the Golden Pencil - is awarded to the artist who has shown exceptional skill in drawing every semester. The panel who determines the recipient consists of the resident art teachers. The prize was first conceived by a drawing teacher at TAS, Udo Vool. The prize was first issued during the fall semester of 2010.
- The 24-hour comics event was launched in 2003 and lasted until 2009. The patron of the event was a TAS art teacher Peeter Krosmann, however, the idea originated from the American cartoonist Scott McCloud. The purpose of the event was to draw a page of a graphic novel in an hour with the ultimate goal of creating 24 pages of material.

## Notable alumni

Many influential artists on the Estonian and international art scene have graduated from Tartu Art School including:

- Ellinor Aiki
- Kalli Kalde
- Kaarel Kurismaa
- Lembit Lõhmus
- Leonhard Merzin
- Enno Ootsing
- Tiit Pääsuke
- Ahti Seppet
- Agaate Veeber
- Kuno Veeber

## Connection to Tartu Art College

Tartu Art College was founded on the 1st of August 2000. It provides undergraduate level art education and is closely linked to Tartu Art School as a large percentage of the TAS graduates continue their studies at the college. The two biggest art schools in Tartu are situated right next to each other and also share a portion of the faculty and the facilities.

## References

1. ↑ "Official website". Archived from the original on 2012-04-20. Retrieved 2012-07-16.
2. ↑ "Ajalugu | Tartu Kunstikool". Archived from the original on 2013-01-06. Retrieved 2012-07-16.

## External links

- Official website
Edit this at Wikidata

<!-- image -->","# Nungia

Genus of spiders

<!-- image -->

| Nungia                    | Nungia                    |
|---------------------------|---------------------------|
| Scientific classification | Scientific classification |
| Domain:                   | Eukaryota                 |
| Kingdom:                  | Animalia                  |
| Phylum:                   | Arthropoda                |
| Subphylum:                | Chelicerata               |
| Class:                    | Arachnida                 |
| Order:                    | Araneae                   |
| Infraorder:               | Araneomorphae             |
| Family:                   | Salticidae                |
| Subfamily:                | Salticinae                |
| Genus:                    | Nungia Zabka, 1985[1]     |
| Diversity                 | Diversity                 |
| 6 species                 | 6 species                 |

Nungia is a genus of Asian jumping spiders containing 6 species,  and was first described by Marek Michał Żabka in 1985.[1][2]

As of November 2022[update], the World Spider Catalog accepted 6 species:

- Nungia epigynalis (Żabka, 1985) - China, Vietnam, Japan
- Nungia hatamensis (Thorell, 1881) - Malaysia, New Guinea
- Nungia modesta (Keyserling, 1883) - Australia (Queensland)
- Nungia papakula (Strand, 1911) - Indonesia (Aru Is.)
- Nungia tangi (Wang &amp; Li, 2022) - China (Hainan)
- Nungia xiaolonghaensis (Cao &amp; Li, 2016) - China

## References

1. 1 2 "Gen. Nungia Zabka, 1985". World Spider Catalog Version 20.0. Natural History Museum Bern. 2019. doi:10.24436/2. Retrieved 2019-08-26.
2. ↑ Żabka, M. (1985). "Systematic and zoogeographic study on the family Salticidae (Araneae) from Viet-Nam". Annales Zoologici, Warszawa. 39: 197-485.

## External links

- Salticidae.org: Diagnostic drawings

| Taxon identifiers   | Taxon identifiers                                                                                                                                                                                                                                                                              |
|---------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Nungia              | Wikidata: Q14647447  Wikispecies: Nungia  AFD: Nungia  BioLib: 491450  CoL: 65W8  EoL: 114368  GBIF: 2174930  iNaturalist: 420493  IRMNG: 1360767  ITIS: 872617  NCBI: 1560443  Open Tree of Life: 3547272  Plazi: D406BF8A-CD66-56E1-8AA8-C518271EDDA6  WSC: urn:lsid:nmbe.ch:spidergen:03098 |

<!-- image -->

- v
- t
- e","# Khlong Tan subdistrict

Khwaeng in Thailand

<!-- image -->

<!-- image -->

<!-- image -->

| Khlong Tan คลองตัน                                                                            | Khlong Tan คลองตัน                                                                            |
|-----------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------|
| Khwaeng                                                                                       | Khwaeng                                                                                       |
| Benjasiri Park                                                                                | Benjasiri Park                                                                                |
| Location in Khlong Toei district                                                              | Location in Khlong Toei district                                                              |
| Coordinates: 13°43′36.1″N 100°34′06.1″E﻿ / ﻿13.726694°N 100.568361°E﻿ / 13.726694; 100.568361 | Coordinates: 13°43′36.1″N 100°34′06.1″E﻿ / ﻿13.726694°N 100.568361°E﻿ / 13.726694; 100.568361 |
| Country                                                                                       | Thailand                                                                                      |
| Province                                                                                      | Bangkok                                                                                       |
| Khet                                                                                          | Khlong Toei                                                                                   |
| Area[1]                                                                                       | Area[1]                                                                                       |
| • Total                                                                                       | 1.895 km2 (0.732 sq mi)                                                                       |
| Population (2021)[2]                                                                          | Population (2021)[2]                                                                          |
| • Total                                                                                       | 10,573                                                                                        |
| • Density                                                                                     | 5,579.42/km2 (14,450.6/sq mi)                                                                 |
| Time zone                                                                                     | UTC+7 (ICT)                                                                                   |
| Postal code                                                                                   | 10110                                                                                         |
| TIS 1099                                                                                      | 103302                                                                                        |

Khlong Tan (Thai: คลองตัน, pronounced [kʰlɔ̄ːŋ tān]) is a khwaeng (subdistrict) in Khlong Toei district, Bangkok. In 2021, it had a population of 10,573 people.

## References

1. ↑ กองยุทธศาสตร์บริหารจัดการ. สำนักยุทธศาสตร์และประเมินผล. กรุงเทพมหานคร. "จำนวนประชากร พื้นที่ ความหนาแน่น จำนวนบ้าน จำแนกตามแขวง ในเขตกรุงเทพมหานคร 2563." สถิติกรุงเทพมหานครประจำปี 2563. Thai: ภาษาไทย
2. ↑ กรมการปกครอง. กระทรวงมหาดไทย. "รายงานสถิติจำนวนประชากรและบ้าน ประจำปี พ.ศ. 2564." [ออนไลน์]. เข้าถึงได้จาก: https://stat.bora.dopa.go.th/stat/statnew/statyear/#/TableTemplate4/Area/statpop?yymm=64&amp;ccDesc=กรุงเทพมหานคร&amp;topic=statpop&amp;ccNo=10&amp;rcodeNo=1033&amp;rcodeDesc=เขตคลองเตย 2564. สืบค้น 3 พฤษภาคม 2565. Thai: ภาษาไทย","# Usman Liaqat

Pakistani cricketer (born 1992)

| Personal information             | Personal information             |
|----------------------------------|----------------------------------|
| Born                             | (1992-05-02) 2 May 1992 (age 32) |
| Source: Cricinfo, 2 October 2018 | Source: Cricinfo, 2 October 2018 |

Usman Liaqat (born 2 May 1992) is a Pakistani cricketer.[1] He made his first-class debut for Multan in the 2012-13 Quaid-e-Azam Trophy on 28 December 2012.[2]

## References

1. ↑ "Usman Liaqat". ESPN Cricinfo. Retrieved 6 October 2018.
2. ↑ "Group I, Quaid-e-Azam Trophy at Islamabad, Dec 28-31 2012". ESPN Cricinfo. Retrieved 6 October 2018.

## External links

- Usman Liaqat at ESPNcricinfo

<!-- image -->

<!-- image -->

- v
- t
- e",...,"# Mannequin (1933 film)

1933 British film

| Mannequin          | Mannequin                                   |
|--------------------|---------------------------------------------|
| Directed by        | George A. Cooper                            |
| Written by         | Charles Bennett                             |
| Produced by        | Julius Hagen                                |
| Starring           | Harold French   Judy Kelly   Diana Beaumont |
| Production company | Twickenham Film Studios                     |
| Distributed by     | RKO Radio Pictures                          |
| Release date       | 5 December 1933 (1933-12-05)                |
| Running time       | 54 minutes                                  |
| Country            | United Kingdom                              |
| Language           | English                                     |

Mannequin is a 1933 British drama film directed by George A. Cooper and starring Harold French, Judy Kelly and Diana Beaumont. It was made at Twickenham Studios in London with sets designed by the art director James A. Carter. Produced as a quota quickie, it was released by the American distributor RKO.[1]

## Synopsis

A boxer leaves his true love for another woman but ultimately returns to her.

## Cast

- Harold French as Peter Tattersall
- Judy Kelly as Heather Trent
- Diana Beaumont as Lady Diana Savage
- Whitmore Humphreys as Billy Armstrong (as Whitmore Humphries)
- Richard Cooper as Lord Bunny Carstairs
- Ben Welden as Chris Dempson
- Faith Bennett as Queenie
- Vera Bogetti as Nancy
- Anna Lee as Babette
- William Pardue as Armstrong's trainer
- Carol Lees as Binkie
- Toni Edgar-Bruce as Mrs. Mannering

## References

1. ↑ Chibnall p.273

## Bibliography

- Chibnall, Steve. Quota Quickies: The Birth of the British 'B' Film. British Film Institute, 2007.
- Low, Rachael. Filmmaking in 1930s Britain. George Allen &amp; Unwin, 1985.
- Wood, Linda. British Films, 1927-1939. British Film Institute, 1986.

## External links

- Mannequin at IMDb
- Mannequin at The British Film Institute

| v t e The films of George A. Cooper                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | v t e The films of George A. Cooper                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |