##### **** These pip installs need to be adapted to use the appropriate release level. Alternatively, The venv running the jupyter lab could be pre-configured with a requirement file that includes the right release. Example for transform developers working from git clone:
```
make venv 
source venv/bin/activate 
pip install jupyterlab
```

In [1]:
%%capture
!pip install pandas

In [2]:
import os
os.environ['S3_ACCESS_KEY']=os.environ['COS_DPK_ACCESS_KEY']
os.environ['S3_SECRET_KEY']=os.environ['COS_DPK_SECRET_KEY']
os.environ['S3_ENDPOINT']= "https://s3.us-south.cloud-object-storage.appdomain.cloud"
input_folder="bucket-wikimedia-1/take6_md"
output_folder="bucket-wikimedia-1/test-MT"

##### ***** Import required classes and modules

In [3]:
from data_processing.data_access import DataAccessS3

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

In [4]:
da=DataAccessS3(config={'input_folder': input_folder,'output_folder': output_folder})
l, _, _=da.get_files_to_process()

In [5]:
import pyarrow.parquet as pq
import pyarrow as pa
import pandas as pd

dataset=None
ndx = 0
for _filename in l:
    byte_array,_=da.get_file(_filename)
    ndx = ndx + 1
    print (f"{ndx}- Processing {_filename}: file size: {len(byte_array)}")
    pqfile=pq.ParquetFile(pa.BufferReader(byte_array))
    patable=pqfile.read().select(['filename', 'hash'])
    if dataset is None:
        dataset=patable.to_pandas()
    else:
        dataset=pd.concat([dataset, patable.to_pandas()], ignore_index=True)

1- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_0.ndjson.parquet: file size: 35053613
2- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_1.ndjson.parquet: file size: 35506589
3- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_10.ndjson.parquet: file size: 34491630
4- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_100.ndjson.parquet: file size: 50950761
5- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_101.ndjson.parquet: file size: 52202646
6- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_102.ndjson.parquet: file size: 52989262
7- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_103.ndjson.parquet: file size: 53085169
8- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_104.ndjson.parquet: file size: 53694756
9- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_105.ndjson.parquet: file size: 53821285
10- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_106.ndjson.parquet: file size: 53146835
11- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_107.ndjson.parquet: file size: 52336178
12- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_108.ndjson.parquet: file size: 53465582
13- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_109.ndjson.parquet: file size: 53389607
14- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_11.ndjson.parquet: file size: 32300861
15- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_110.ndjson.parquet: file size: 52801123
16- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_111.ndjson.parquet: file size: 53666576
17- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_112.ndjson.parquet: file size: 52129234
18- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_113.ndjson.parquet: file size: 52113503
19- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_114.ndjson.parquet: file size: 50470716
20- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_115.ndjson.parquet: file size: 50420361
21- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_116.ndjson.parquet: file size: 51995486
22- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_117.ndjson.parquet: file size: 51654327
23- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_118.ndjson.parquet: file size: 52849524
24- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_119.ndjson.parquet: file size: 52977955
25- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_12.ndjson.parquet: file size: 33164891
26- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_120.ndjson.parquet: file size: 52333201
27- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_121.ndjson.parquet: file size: 50803402
28- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_122.ndjson.parquet: file size: 51451827
29- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_123.ndjson.parquet: file size: 50558701
30- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_124.ndjson.parquet: file size: 52954500
31- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_125.ndjson.parquet: file size: 53993895
32- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_126.ndjson.parquet: file size: 53542265
33- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_127.ndjson.parquet: file size: 53347954
34- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_128.ndjson.parquet: file size: 53984834
35- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_129.ndjson.parquet: file size: 52395407
36- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_13.ndjson.parquet: file size: 32775564
37- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_130.ndjson.parquet: file size: 51025806
38- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_131.ndjson.parquet: file size: 50934964
39- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_132.ndjson.parquet: file size: 51847328
40- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_133.ndjson.parquet: file size: 52572095
41- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_134.ndjson.parquet: file size: 52016169
42- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_135.ndjson.parquet: file size: 52479614
43- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_136.ndjson.parquet: file size: 52656567
44- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_137.ndjson.parquet: file size: 53104020
45- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_138.ndjson.parquet: file size: 52956070
46- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_139.ndjson.parquet: file size: 51120054
47- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_14.ndjson.parquet: file size: 31397742
48- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_140.ndjson.parquet: file size: 50866075
49- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_141.ndjson.parquet: file size: 50939929
50- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_142.ndjson.parquet: file size: 53038450
51- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_143.ndjson.parquet: file size: 53518343
52- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_144.ndjson.parquet: file size: 54128855
53- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_145.ndjson.parquet: file size: 53409236
54- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_146.ndjson.parquet: file size: 53740763
55- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_147.ndjson.parquet: file size: 54185032
56- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_148.ndjson.parquet: file size: 53474298
57- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_149.ndjson.parquet: file size: 52914316
58- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_15.ndjson.parquet: file size: 31145378
59- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_150.ndjson.parquet: file size: 53251448
60- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_151.ndjson.parquet: file size: 53135923
61- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_152.ndjson.parquet: file size: 53581233
62- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_153.ndjson.parquet: file size: 52744565
63- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_154.ndjson.parquet: file size: 53116707
64- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_155.ndjson.parquet: file size: 53530604
65- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_156.ndjson.parquet: file size: 53645998
66- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_157.ndjson.parquet: file size: 53035546
67- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_158.ndjson.parquet: file size: 52541772
68- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_159.ndjson.parquet: file size: 52265446
69- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_16.ndjson.parquet: file size: 34064779
70- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_160.ndjson.parquet: file size: 52539290
71- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_161.ndjson.parquet: file size: 54123730
72- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_162.ndjson.parquet: file size: 54268681
73- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_163.ndjson.parquet: file size: 54285617
74- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_164.ndjson.parquet: file size: 53170057
75- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_165.ndjson.parquet: file size: 53706014
76- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_166.ndjson.parquet: file size: 52629327
77- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_167.ndjson.parquet: file size: 53126732
78- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_168.ndjson.parquet: file size: 53722500
79- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_169.ndjson.parquet: file size: 53266690
80- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_17.ndjson.parquet: file size: 34974260
81- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_170.ndjson.parquet: file size: 53475232
82- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_171.ndjson.parquet: file size: 52918853
83- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_172.ndjson.parquet: file size: 51778513
84- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_173.ndjson.parquet: file size: 52158666
85- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_174.ndjson.parquet: file size: 52260864
86- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_175.ndjson.parquet: file size: 52011476
87- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_176.ndjson.parquet: file size: 53206662
88- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_177.ndjson.parquet: file size: 54471882
89- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_178.ndjson.parquet: file size: 53670535
90- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_179.ndjson.parquet: file size: 53326714
91- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_18.ndjson.parquet: file size: 31700795
92- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_180.ndjson.parquet: file size: 52820309
93- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_181.ndjson.parquet: file size: 52951620
94- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_182.ndjson.parquet: file size: 53358177
95- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_183.ndjson.parquet: file size: 54249557
96- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_184.ndjson.parquet: file size: 53512031
97- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_185.ndjson.parquet: file size: 52780228
98- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_186.ndjson.parquet: file size: 53332014
99- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_187.ndjson.parquet: file size: 53214395
100- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_188.ndjson.parquet: file size: 53658573
101- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_189.ndjson.parquet: file size: 54303826
102- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_19.ndjson.parquet: file size: 32160423
103- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_190.ndjson.parquet: file size: 54576969
104- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_191.ndjson.parquet: file size: 55118038
105- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_192.ndjson.parquet: file size: 54180517
106- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_193.ndjson.parquet: file size: 54973006
107- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_194.ndjson.parquet: file size: 54839335
108- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_195.ndjson.parquet: file size: 53735561
109- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_196.ndjson.parquet: file size: 54862135
110- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_197.ndjson.parquet: file size: 54248740
111- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_198.ndjson.parquet: file size: 53676902
112- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_199.ndjson.parquet: file size: 53432339
113- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_2.ndjson.parquet: file size: 35194556
114- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_20.ndjson.parquet: file size: 34641954
115- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_200.ndjson.parquet: file size: 55064611
116- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_201.ndjson.parquet: file size: 55774613
117- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_202.ndjson.parquet: file size: 54790194
118- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_203.ndjson.parquet: file size: 55804634
119- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_204.ndjson.parquet: file size: 56454005
120- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_205.ndjson.parquet: file size: 55453006
121- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_206.ndjson.parquet: file size: 54604548
122- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_207.ndjson.parquet: file size: 53156216
123- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_208.ndjson.parquet: file size: 52492273
124- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_209.ndjson.parquet: file size: 53428570
125- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_21.ndjson.parquet: file size: 38187021
126- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_210.ndjson.parquet: file size: 53041816
127- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_211.ndjson.parquet: file size: 55019679
128- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_212.ndjson.parquet: file size: 53574585
129- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_213.ndjson.parquet: file size: 54276559
130- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_214.ndjson.parquet: file size: 54875017
131- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_215.ndjson.parquet: file size: 54338316
132- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_216.ndjson.parquet: file size: 54390121
133- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_217.ndjson.parquet: file size: 54737684
134- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_218.ndjson.parquet: file size: 55362109
135- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_219.ndjson.parquet: file size: 55728916
136- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_22.ndjson.parquet: file size: 43509414
137- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_220.ndjson.parquet: file size: 53696793
138- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_221.ndjson.parquet: file size: 54508112
139- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_222.ndjson.parquet: file size: 53856247
140- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_223.ndjson.parquet: file size: 52227861
141- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_224.ndjson.parquet: file size: 52541627
142- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_225.ndjson.parquet: file size: 54017532
143- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_226.ndjson.parquet: file size: 52820684
144- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_227.ndjson.parquet: file size: 55163102
145- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_228.ndjson.parquet: file size: 54991907
146- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_229.ndjson.parquet: file size: 55498278
147- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_23.ndjson.parquet: file size: 40335174
148- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_230.ndjson.parquet: file size: 56340531
149- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_231.ndjson.parquet: file size: 55953400
150- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_232.ndjson.parquet: file size: 57356496
151- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_233.ndjson.parquet: file size: 56336364
152- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_234.ndjson.parquet: file size: 56971196
153- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_235.ndjson.parquet: file size: 56608054
154- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_236.ndjson.parquet: file size: 55927402
155- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_237.ndjson.parquet: file size: 56236742
156- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_238.ndjson.parquet: file size: 56728735
157- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_239.ndjson.parquet: file size: 55851646
158- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_24.ndjson.parquet: file size: 33378405
159- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_240.ndjson.parquet: file size: 55489866
160- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_241.ndjson.parquet: file size: 56311509
161- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_242.ndjson.parquet: file size: 56064901
162- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_243.ndjson.parquet: file size: 55886783
163- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_244.ndjson.parquet: file size: 56603977
164- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_245.ndjson.parquet: file size: 55835704
165- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_246.ndjson.parquet: file size: 57302707
166- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_247.ndjson.parquet: file size: 56839648
167- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_248.ndjson.parquet: file size: 56186477
168- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_249.ndjson.parquet: file size: 57343448
169- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_25.ndjson.parquet: file size: 32325183
170- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_250.ndjson.parquet: file size: 56079841
171- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_251.ndjson.parquet: file size: 57145242
172- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_252.ndjson.parquet: file size: 56064613
173- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_253.ndjson.parquet: file size: 56263556
174- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_254.ndjson.parquet: file size: 56646220
175- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_255.ndjson.parquet: file size: 56395033
176- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_256.ndjson.parquet: file size: 55510669
177- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_257.ndjson.parquet: file size: 56283645
178- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_258.ndjson.parquet: file size: 55471394
179- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_259.ndjson.parquet: file size: 54956217
180- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_26.ndjson.parquet: file size: 32553540
181- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_260.ndjson.parquet: file size: 55775797
182- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_261.ndjson.parquet: file size: 56505990
183- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_262.ndjson.parquet: file size: 55860026
184- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_263.ndjson.parquet: file size: 55813636
185- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_264.ndjson.parquet: file size: 56857505
186- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_265.ndjson.parquet: file size: 56974073
187- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_266.ndjson.parquet: file size: 58449696
188- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_267.ndjson.parquet: file size: 60028519
189- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_268.ndjson.parquet: file size: 59521615
190- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_269.ndjson.parquet: file size: 59854046
191- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_27.ndjson.parquet: file size: 33784649
192- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_270.ndjson.parquet: file size: 61310563
193- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_271.ndjson.parquet: file size: 62116397
194- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_272.ndjson.parquet: file size: 62780466
195- Processing bucket-wikimedia-1/take6_md/enwiki_namespace_0_273.ndjson.parquet: file size: 62913390

In [6]:
hash_counts=dataset['hash'].value_counts()
dataset['hash_count']=dataset['hash'].map(hash_counts)
dataset.sort_values(by='hash_count', ascending=False)

,filename,hash,hash_count
5359647,enwiki_namespace_0_391_3838.html,06f9b993ca3e8324d22b152b154671f8e2637cb802a4de...,25
5322705,enwiki_namespace_0_389_5065.html,06f9b993ca3e8324d22b152b154671f8e2637cb802a4de...,25
5362312,enwiki_namespace_0_391_6503.html,06f9b993ca3e8324d22b152b154671f8e2637cb802a4de...,25
5305911,enwiki_namespace_0_387_547.html,06f9b993ca3e8324d22b152b154671f8e2637cb802a4de...,25
5310785,enwiki_namespace_0_387_5421.html,06f9b993ca3e8324d22b152b154671f8e2637cb802a4de...,25
...,...,...,...
2377012,enwiki_namespace_0_185_8250.html,a783df82d337d7e6c0ba476b8a14c0592742503967be17...,1
2377011,enwiki_namespace_0_185_8249.html,2c5e0189312dcb578f9a171b0624e327e989fc49d9e3d3...,1
2377010,enwiki_namespace_0_185_8248.html,30dd51f4bff99670e8e5dcedc462e81dd1e329cc160c97...,1
2377009,enwiki_namespace_0_185_8247.html,c7531ff32e4bdf6674a38376afeb0b4c4af2f5ab3e8466...,1
7128272,enwiki_namespace_0_99_24190.html,932992ec9e21d937ec10cf386593b1b20346dd52849898...,1

In [16]:
dataset.drop_duplicates(subset=['hash'])

,filename,hash,hash_count
0,enwiki_namespace_0_0_0.html,756337333d16a5817f98cd6893580a5bfc65609df400e2...,1
1,enwiki_namespace_0_0_1.html,bf001f7604b81e3ce37d8e3120fe9465bb79fce7d1a162...,1
2,enwiki_namespace_0_0_2.html,0f3afa4377b6f4b82fd7356cb3be31649ea709a89f906c...,1
3,enwiki_namespace_0_0_3.html,90d6286d3e8f0c109cd5179badc36a74741d2bc53bf344...,1
4,enwiki_namespace_0_0_4.html,0b91160be7fc42e994d122fff3398f1b9a5980e5cf4248...,1
...,...,...,...
7128268,enwiki_namespace_0_99_24186.html,9fc2b14d324a7f5ea10d572a423dcc66203d94081da751...,1
7128269,enwiki_namespace_0_99_24187.html,be51be07000955d5572ebf664452a734f30909ca93f2c2...,1
7128270,enwiki_namespace_0_99_24188.html,a8af1432c181d6bacab82eb4e49df81637d050206db234...,1
7128271,enwiki_namespace_0_99_24189.html,73ab125dbe590b3c8bd7987e44a07544b2b52dd65b2eb7...,1
7128272,enwiki_namespace_0_99_24190.html,932992ec9e21d937ec10cf386593b1b20346dd52849898...,1

In [7]:
dataset.drop_duplicates(subset=['hash'])

,filename,hash,hash_count
0,enwiki_namespace_0_0_0.html,756337333d16a5817f98cd6893580a5bfc65609df400e2...,1
1,enwiki_namespace_0_0_1.html,bf001f7604b81e3ce37d8e3120fe9465bb79fce7d1a162...,1
2,enwiki_namespace_0_0_2.html,0f3afa4377b6f4b82fd7356cb3be31649ea709a89f906c...,1
3,enwiki_namespace_0_0_3.html,90d6286d3e8f0c109cd5179badc36a74741d2bc53bf344...,1
4,enwiki_namespace_0_0_4.html,0b91160be7fc42e994d122fff3398f1b9a5980e5cf4248...,1
...,...,...,...
7128268,enwiki_namespace_0_99_24186.html,9fc2b14d324a7f5ea10d572a423dcc66203d94081da751...,1
7128269,enwiki_namespace_0_99_24187.html,be51be07000955d5572ebf664452a734f30909ca93f2c2...,1
7128270,enwiki_namespace_0_99_24188.html,a8af1432c181d6bacab82eb4e49df81637d050206db234...,1
7128271,enwiki_namespace_0_99_24189.html,73ab125dbe590b3c8bd7987e44a07544b2b52dd65b2eb7...,1
7128272,enwiki_namespace_0_99_24190.html,932992ec9e21d937ec10cf386593b1b20346dd52849898...,1

In [17]:
byte_array,_=da.get_file(f"{input_folder}/enwiki_namespace_0_391.ndjson.parquet")
_hash=dataset.sort_values(by='hash_count', ascending=False)['hash'].iloc[0]
df=pq.ParquetFile(pa.BufferReader(byte_array)).read().to_pandas()
df[df['hash']==_hash][['filename','contents']]

,filename,contents
3405,enwiki_namespace_0_391_3414.html,# Bill Charlap\n\nAmerican jazz pianist (born ...
3625,enwiki_namespace_0_391_3634.html,# Bill Charlap\n\nAmerican jazz pianist (born ...
3829,enwiki_namespace_0_391_3838.html,# Bill Charlap\n\nAmerican jazz pianist (born ...
4030,enwiki_namespace_0_391_4039.html,# Bill Charlap\n\nAmerican jazz pianist (born ...
4278,enwiki_namespace_0_391_4287.html,# Bill Charlap\n\nAmerican jazz pianist (born ...
6494,enwiki_namespace_0_391_6503.html,# Bill Charlap\n\nAmerican jazz pianist (born ...
6836,enwiki_namespace_0_391_6845.html,# Bill Charlap\n\nAmerican jazz pianist (born ...