##### **** These pip installs need to be adapted to use the appropriate release level. Alternatively, The venv running the jupyter lab could be pre-configured with a requirement file that includes the right release. Example for transform developers working from git clone:
```
make venv
source venv/bin/activate && pip install jupyterlab
```

In [1]:
%%capture
## This is here as a reference only
# Users and application developers must use the right tag for the latest from pypi
#!pip install data-prep-toolkit
#!pip install data-prep-toolkit-transforms
!pip install polars

##### ***** Import required Classes and modules

In [2]:
from dpk_collapse.ray.runtime import Collapse

##### ***** Setup runtime parameters for this transform
We will only provide a description for the parameters used in this example. For a complete list of parameters, please refer to the README.md for this transform:
|parameter:type | value | description |
|-|-|-|
| input_folder:str | \${PWD}/test-data/input/ | folder that contains the input parquet files for the collpase algorithm |
| output_folder:str | \${PWD}/test-data/output/ | folder that contains the all the intermediate results and the output parquet files for the collapse algorithm |
| collapse_input_columns: list[str] | user defined | list of column names to join together into a single column |
| collpase_output_column:str | user defined | column name that will be created to receive the joined text |
| collpase_field_seperator:str | user defined | Seperator used for concatenated text |

In [3]:
Collapse(
    input_folder="test-data/input",
    output_folder="test-data/output",
    collapse_input_columns=["title","contents"],
    collapse_output_column="text",
    run_locally=True,
).transform()

10:48:14 INFO - parameters are : {'collapse_input_columns': ['title', 'contents'], 'collapse_output_column': 'text', 'collapse_field_seperator': '\n', 'collapse_retain_all': None} at "/Users/touma/data-prep-kit-pkg/transforms/universal/collapse/dpk_collapse/transform.py:139"
10:48:14 INFO - pipeline id pipeline_id
10:48:14 INFO - code location None
10:48:14 INFO - number of workers 1 worker options {'num_cpus': 0.8, 'max_restarts': -1}
10:48:14 INFO - actor creation delay 0
10:48:14 INFO - job details {'job category': 'preprocessing', 'job name': 'collapse', 'job type': 'ray', 'job id': 'job_id'}
10:48:14 INFO - data factory data_ is using local data access: input_folder - test-data/input output_folder - test-data/output
10:48:14 INFO - data factory data_ max_files -1, n_sample -1
10:48:14 INFO - data factory data_ Not using data sets, checkpointing False, max files -1, random samples -1, files to use ['.parquet'], files to checkpoint ['.parquet']
10:48:14 INFO - Running locally
2025-04-19 10:48:15,216	INFO worker.py:1777 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
(orchestrate pid=61234) 10:48:16 INFO - orchestrator started at 2025-04-19 10:48:16
(orchestrate pid=61234) 10:48:16 INFO - Number of files is 1, source profile {'max_file_size': 0.034458160400390625, 'min_file_size': 0.034458160400390625, 'total_file_size': 0.034458160400390625}
(orchestrate pid=61234) 10:48:16 INFO - Cluster resources: {'cpus': 12, 'gpus': 0, 'memory': 19.676039123907685, 'object_store': 2.0}
(orchestrate pid=61234) 10:48:16 INFO - Number of workers - 1 with {'num_cpus': 0.8, 'max_restarts': -1} each
(RayTransformFileProcessor pid=61279) 10:48:16 DEBUG - input columns: ['title', 'contents'] output column: text field seperator: '
(RayTransformFileProcessor pid=61279) ' retain all: None  at "/Users/touma/data-prep-kit-pkg/transforms/universal/collapse/dpk_collapse/transform.py:54"
(orchestrate pid=61234) 10:48:17 INFO - Completed 0 files (0.0%)  in 0.0 min. Waiting for completion
(orchestrate pid=61234) 10:48:17 INFO - Completed processing 1 files in 0.004 min
(orchestrate pid=61234) 10:48:17 INFO - done flushing in 0.001 sec
(raylet) [2025-04-19 10:48:25,254 E 61228 7928441] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2025-04-19_10-48-14_269914_61190 is over 95% full, available space: 15155265536; capacity: 494662586368. Object creation will fail if spilling is required.
10:48:27 INFO - Completed execution in 0.223 min, execution result 0

0

##### **** The specified folder will include the transformed parquet files.

In [4]:
import glob
glob.glob("test-data/output/*")

['test-data/output/sample1.parquet', 'test-data/output/metadata.json']

***** print the input data

In [5]:
import os
import polars as pl
input_df = pl.read_parquet(os.path.join(os.path.abspath(""), "test-data/input/sample1.parquet"))
input_df.to_pandas()

,Unnamed: 0.1,Unnamed: 0,document_id,document,title,contents,language,doc_title,full_domain,filename,...,scope,tags,topics,contents_sha2,version,extras,dataset,domain,date_crawled,date_downloaded
0,0,0,d07817ed05f795177bfc4952b11fa3e21cbba9a92ed440...,s3://blue-pile/blue-pile-raw/5_ibm_internal/0_...,https://www.ibm.com/docs/en/zvm/7.2?topic=subc...,Making a Selective Change Suppose you want to ...,en,Making a Selective Change,ibm_internal,NaN,...,ibmdocs,NaN,NaN,841d761c46cde491b9642b0eca25cd164fc32da24c6c4e...,1.0.1,NaN,ibm.com,internal,2023-07-27 05:00:00+00:00,2023-09-25 05:00:00+00:00
1,1,1,3e4d6c6c89dd166c88d79a6cbe3d90c8db2c9847fca198...,s3://blue-pile/blue-pile-raw/5_ibm_internal/0_...,https://www.ibm.com/docs/en/ztpf/2022?topic=me...,"NKEY - NNCS NKEY0004W SINCE MAXSRT IS ZERO, ke...",en,NKEY - NNCS,ibm_internal,NaN,...,ibmdocs,NaN,NaN,ebfb721ab47c49c13d4b9b8268dc1aa8dd62089c1be25e...,1.0.1,NaN,ibm.com,internal,2023-07-27 05:00:00+00:00,2023-09-25 05:00:00+00:00
2,2,2,c86996cf20920d0955a38580abb650b00d0e1df5f7bd98...,s3://blue-pile/blue-pile-raw/5_ibm_internal/0_...,https://www.ibm.com/docs/en/ztpf/2021?topic=nt...,"NSPA0014E REJECTED, SYSTEM IS BELOW 1052 STATE...",en,NSPA0014E,ibm_internal,NaN,...,ibmdocs,NaN,NaN,79c94bb45bfe357042bcf1a56ae75f6545f0ffe2d6b324...,1.0.1,NaN,ibm.com,internal,2023-07-27 05:00:00+00:00,2023-09-25 05:00:00+00:00
3,3,3,c86996cf20920d0955a38580abb650b00d0e1df5f7bd98...,s3://blue-pile/blue-pile-raw/5_ibm_internal/0_...,https://www.ibm.com/docs/en/ztpf/2021?topic=nt...,"NSPA0014E REJECTED, SYSTEM IS BELOW 1052 STATE...",en,NSPA0014E,ibm_internal,NaN,...,ibmdocs,NaN,NaN,79c94bb45bfe357042bcf1a56ae75f6545f0ffe2d6b324...,1.0.1,NaN,ibm.com,internal,2023-07-27 05:00:00+00:00,2023-09-25 05:00:00+00:00
4,4,4,3e4d6c6c89dd166c88d79a6cbe3d90c8db2c9847fca198...,s3://blue-pile/blue-pile-raw/5_ibm_internal/0_...,https://www.ibm.com/docs/en/ztpf/2022?topic=me...,"NKEY - NNCS NKEY0004W SINCE MAXSRT IS ZERO, ke...",en,NKEY - NNCS,ibm_internal,NaN,...,ibmdocs,NaN,NaN,ebfb721ab47c49c13d4b9b8268dc1aa8dd62089c1be25e...,1.0.1,NaN,ibm.com,internal,2023-07-27 05:00:00+00:00,2023-09-25 05:00:00+00:00

***** print the output result

In [6]:
output_df = pl.read_parquet(os.path.join(os.path.abspath(""), "test-data/output/sample1.parquet"))
output_df.to_pandas()

,Unnamed: 0.1,Unnamed: 0,document_id,document,language,doc_title,full_domain,filename,download_code_version,download_config,...,tags,topics,contents_sha2,version,extras,dataset,domain,date_crawled,date_downloaded,text
0,0,0,d07817ed05f795177bfc4952b11fa3e21cbba9a92ed440...,s3://blue-pile/blue-pile-raw/5_ibm_internal/0_...,en,Making a Selective Change,ibm_internal,NaN,https://raw.github.ibm.com/ai-models-data/data...,screen -dm bash -c 'python ibm_com_download.py',...,NaN,NaN,841d761c46cde491b9642b0eca25cd164fc32da24c6c4e...,1.0.1,NaN,ibm.com,internal,2023-07-27 05:00:00+00:00,2023-09-25 05:00:00+00:00,https://www.ibm.com/docs/en/zvm/7.2?topic=subc...
1,1,1,3e4d6c6c89dd166c88d79a6cbe3d90c8db2c9847fca198...,s3://blue-pile/blue-pile-raw/5_ibm_internal/0_...,en,NKEY - NNCS,ibm_internal,NaN,https://raw.github.ibm.com/ai-models-data/data...,screen -dm bash -c 'python ibm_com_download.py',...,NaN,NaN,ebfb721ab47c49c13d4b9b8268dc1aa8dd62089c1be25e...,1.0.1,NaN,ibm.com,internal,2023-07-27 05:00:00+00:00,2023-09-25 05:00:00+00:00,https://www.ibm.com/docs/en/ztpf/2022?topic=me...
2,2,2,c86996cf20920d0955a38580abb650b00d0e1df5f7bd98...,s3://blue-pile/blue-pile-raw/5_ibm_internal/0_...,en,NSPA0014E,ibm_internal,NaN,https://raw.github.ibm.com/ai-models-data/data...,screen -dm bash -c 'python ibm_com_download.py',...,NaN,NaN,79c94bb45bfe357042bcf1a56ae75f6545f0ffe2d6b324...,1.0.1,NaN,ibm.com,internal,2023-07-27 05:00:00+00:00,2023-09-25 05:00:00+00:00,https://www.ibm.com/docs/en/ztpf/2021?topic=nt...
3,3,3,c86996cf20920d0955a38580abb650b00d0e1df5f7bd98...,s3://blue-pile/blue-pile-raw/5_ibm_internal/0_...,en,NSPA0014E,ibm_internal,NaN,https://raw.github.ibm.com/ai-models-data/data...,screen -dm bash -c 'python ibm_com_download.py',...,NaN,NaN,79c94bb45bfe357042bcf1a56ae75f6545f0ffe2d6b324...,1.0.1,NaN,ibm.com,internal,2023-07-27 05:00:00+00:00,2023-09-25 05:00:00+00:00,https://www.ibm.com/docs/en/ztpf/2021?topic=nt...
4,4,4,3e4d6c6c89dd166c88d79a6cbe3d90c8db2c9847fca198...,s3://blue-pile/blue-pile-raw/5_ibm_internal/0_...,en,NKEY - NNCS,ibm_internal,NaN,https://raw.github.ibm.com/ai-models-data/data...,screen -dm bash -c 'python ibm_com_download.py',...,NaN,NaN,ebfb721ab47c49c13d4b9b8268dc1aa8dd62089c1be25e...,1.0.1,NaN,ibm.com,internal,2023-07-27 05:00:00+00:00,2023-09-25 05:00:00+00:00,https://www.ibm.com/docs/en/ztpf/2022?topic=me...