##### 1 • Import the transform runtime and utilities

In [1]:
import pandas
from dpk_enrichment.runtime import Enrichment
from dpk_enrichment.transform import get_transform_params

##### 2 • Required parameters for the transform
| Name  | Default Value | Description |
|------------|----------|--------------|
| **enrichment_content_column_name** | **text** | The column with the content to process. |
| **enrichment_lang_column_name** | **lang** | The column name with language identifier for the content. Some of the feature computations require tokenized text as input, the value in this field is used to select the appropritae tokenizer. |
| **enrichment_output_column_prefix** | _not set_ | A prefix for the names of all the output columns. Additionally each column can be explicitedly renamed, or if set to an emtpy string omitted from the output altogether. |

##### 3 • The parametes to set output column names of the computed features

In [8]:
params = [(f"enrichment_{n[0]}", n[2]) for n in get_transform_params() if n[0] not in ["content_column_name", "lang_column_name", "output_column_prefix"]]
pandas.DataFrame(dict(parameter=[p[0] for p in params], value=[p[1] for p in params]))

,parameter,value
0,enrichment_num_newlines_column_name,num_newlines
1,enrichment_num_paragraphs_column_name,num_paragraphs
2,enrichment_num_words_column_name,num_words
3,enrichment_num_chars_column_name,num_chars
4,enrichment_total_non_newline_chars_column_name,total_non_newline_chars
5,enrichment_avg_word_length_column_name,avg_word_length
6,enrichment_avg_paragraph_length_chars_column_name,avg_paragraph_length_chars
7,enrichment_avg_paragraph_length_words_column_name,avg_paragraph_length_words
8,enrichment_alphanumeric_char_ratio_column_name,alphanumeric_char_ratio
9,enrichment_control_char_ratio_column_name,control_char_ratio
10,enrichment_punctuation_char_ratio_column_name,punctuation_char_ratio
11,enrichment_other_symbol_char_ratio_column_name,other_symbol_char_ratio
12,enrichment_tabs_word_ratio_column_name,tabs_word_ratio
13,enrichment_hashes_word_ratio_column_name,hashes_word_ratio
14,enrichment_ellipsis_ratio_column_name,ellipsis_ratio
15,enrichment_bulletpoint_ratio_column_name,bulletpoint_ratio
16,enrichment_dup_paragraphs_ratio_column_name,dup_paragraphs_ratio
17,enrichment_dup_paragraphs_char_ratio_column_name,dup_paragraphs_char_ratio
18,enrichment_top_2_gram_char_ratio_column_name,top_2_gram_char_ratio
19,enrichment_top_3_gram_char_ratio_column_name,top_3_gram_char_ratio
20,enrichment_top_4_gram_char_ratio_column_name,top_4_gram_char_ratio
21,enrichment_dup_5_gram_char_ratio_column_name,dup_5_gram_char_ratio
22,enrichment_dup_6_gram_char_ratio_column_name,dup_6_gram_char_ratio
23,enrichment_dup_7_gram_char_ratio_column_name,dup_7_gram_char_ratio
24,enrichment_dup_8_gram_char_ratio_column_name,dup_8_gram_char_ratio
25,enrichment_dup_9_gram_char_ratio_column_name,dup_9_gram_char_ratio
26,enrichment_dup_10_gram_char_ratio_column_name,dup_10_gram_char_ratio

##### 4 • Setup the transform

In [3]:
transform = Enrichment(
    enrichment_content_column_name="text",
    enrichment_lang_column_name="lang",
    enrichment_output_column_prefix="e_",
    input_folder="test-data/input", 
    output_folder="output" 
)

##### 5 • Run

In [9]:
transform.transform()

12:32:34 INFO - Enrichment parameters are: {"output_column_prefix": "e_", "content_column_name": "text", "lang_column_name": "lang", "num_newlines_column_name": "num_newlines", "num_paragraphs_column_name": "num_paragraphs", "num_words_column_name": "num_words", "num_chars_column_name": "num_chars", "total_non_newline_chars_column_name": "total_non_newline_chars", "avg_word_length_column_name": "avg_word_length", "avg_paragraph_length_chars_column_name": "avg_paragraph_length_chars", "avg_paragraph_length_words_column_name": "avg_paragraph_length_words", "alphanumeric_char_ratio_column_name": "alphanumeric_char_ratio", "control_char_ratio_column_name": "control_char_ratio", "punctuation_char_ratio_column_name": "punctuation_char_ratio", "other_symbol_char_ratio_column_name": "other_symbol_char_ratio", "tabs_word_ratio_column_name": "tabs_word_ratio", "hashes_word_ratio_column_name": "hashes_word_ratio", "ellipsis_ratio_column_name": "ellipsis_ratio", "bulletpoint_ratio_column_name": "bulletpoint_ratio", "dup_paragraphs_ratio_column_name": "dup_paragraphs_ratio", "dup_paragraphs_char_ratio_column_name": "dup_paragraphs_char_ratio", "top_2_gram_char_ratio_column_name": "top_2_gram_char_ratio", "top_3_gram_char_ratio_column_name": "top_3_gram_char_ratio", "top_4_gram_char_ratio_column_name": "top_4_gram_char_ratio", "dup_5_gram_char_ratio_column_name": "dup_5_gram_char_ratio", "dup_6_gram_char_ratio_column_name": "dup_6_gram_char_ratio", "dup_7_gram_char_ratio_column_name": "dup_7_gram_char_ratio", "dup_8_gram_char_ratio_column_name": "dup_8_gram_char_ratio", "dup_9_gram_char_ratio_column_name": "dup_9_gram_char_ratio", "dup_10_gram_char_ratio_column_name": "dup_10_gram_char_ratio"}
12:32:34 INFO - pipeline id pipeline_id
12:32:34 INFO - code location None
12:32:34 INFO - data factory data_ is using local data access: input_folder - test-data/input output_folder - output
12:32:34 INFO - data factory data_ max_files -1, n_sample -1
12:32:34 INFO - data factory data_ Not using data sets, checkpointing False, max files -1, random samples -1, files to use ['.parquet'], files to checkpoint ['.parquet']
12:32:34 INFO - orchestrator enrichment started at 2025-03-12 12:32:34
12:32:34 INFO - Number of files is 2, source profile {'max_file_size': 0.21838951110839844, 'min_file_size': 0.1921825408935547, 'total_file_size': 0.4105720520019531}
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/cpendus/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
12:32:35 INFO - Completed 1 files (50.0%) in 0.014 min
12:32:37 INFO - Completed 2 files (100.0%) in 0.037 min
12:32:37 INFO - Done processing 2 files, waiting for flush() completion.
12:32:37 INFO - done flushing in 0.0 sec
12:32:37 INFO - Completed execution in 0.037 min, execution result 0

0

##### 6 • Show the output with the computed features

In [10]:
pandas.read_parquet('output/1.parquet', engine='pyarrow')

,text,lang,e_lid_score,e_num_newlines,e_num_paragraphs,e_num_words,e_num_chars,e_total_non_newline_chars,e_avg_word_length,e_avg_paragraph_length_chars,...,e_dup_paragraphs_char_ratio,e_top_2_gram_char_ratio,e_top_3_gram_char_ratio,e_top_4_gram_char_ratio,e_dup_5_gram_char_ratio,e_dup_6_gram_char_ratio,e_dup_7_gram_char_ratio,e_dup_8_gram_char_ratio,e_dup_9_gram_char_ratio,e_dup_10_gram_char_ratio
0,Alisha // Twenty two // California\nThis is my...,en,0.999,0,1,565,2467,2467,3.534513,2467.0,...,0.0,0.016026,0.019231,0.025641,0.005342,0.000000,0.000000,0.000000,0.000000,0.000000
1,December 2020 – Low Interest Payday Loans KZDO...,en,0.998,0,1,395,2100,2100,4.440506,2100.0,...,0.0,0.023795,0.045211,0.045211,0.084474,0.086258,0.097561,0.088638,0.056514,0.035098
2,terminology com share|improve this question ed...,en,0.999,0,1,290,1570,1570,4.565517,1570.0,...,0.0,0.012698,0.031746,0.019048,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,"Wilmore Road Nicholasville, KY home and proper...",en,0.966,0,1,660,4043,4043,5.259091,4043.0,...,0.0,0.320049,0.454323,0.291845,0.455855,0.371551,0.172900,0.207235,0.224402,0.237278
4,'I went from a screaming room of people to dea...,en,0.999,0,1,281,1594,1594,4.754448,1594.0,...,0.0,0.009288,0.008514,0.010062,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Khubz (Traditional Iraqi Bread) - shosholuv\nK...,en,0.999,0,1,534,2726,2726,4.211610,2726.0,...,0.0,0.020737,0.011982,0.013364,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
96,Property tax payments must be federally post m...,en,0.999,0,1,216,1121,1121,4.324074,1121.0,...,0.0,0.013514,0.036036,0.040541,0.023649,0.000000,0.000000,0.000000,0.000000,0.000000
97,All About Bail Bonds Offers Assistance of Expe...,en,0.999,0,1,437,2369,2369,4.556064,2369.0,...,0.0,0.057351,0.066736,0.052138,0.058916,0.049531,0.040146,0.021898,0.026069,0.027112
98,Windies stuttering after conceding a massive l...,en,0.999,0,1,967,4974,4974,4.199586,4974.0,...,0.0,0.012030,0.019549,0.021053,0.016040,0.009774,0.000000,0.000000,0.000000,0.000000
99,13 Tips How to Reduce Double Chin & Face Fat F...,en,0.998,0,1,351,1763,1763,4.128205,1763.0,...,0.0,0.055596,0.023827,0.034657,0.013718,0.000000,0.000000,0.000000,0.000000,0.000000